apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master-labels
  labels:
    name: redis-master-labels
spec:
  replicas: 1
  selector:
    name: redis-master-labels
  template:
    metadata:
      labels:
        name: redis-master-labels
    spec:
      containers:
      - name: master-labels
        image: kubeguide/redis-master
        ports:
        - containerPort: 6379
      nodeSelector:
        zone: north
