apiVersion: v1
kind: Pod
metadata:
  name: pod-with-healthcheck1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/sh
            - -c
            - 'echo Healty > /usr/share/nginx/html/healthz'
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      initialDelaySeconds: 30
      timeoutSeconds: 1