apiVersion: v1
kind: Pod
metadata:
  name: cm-test-app1
spec:
  containers:
  - name: cm-test-app1
    image: kubeguide/tomcat-app:v1
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: serverxml
      mountPath: /configfiles
  volumes:
  - name: serverxml
    configMap:
      name: cm-appconfigfiles