apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-volume
  labels:
    zone: us-est-coast
    cluster: test-cluster
    rack: rack-22
  annotations:
    build: two
    builder: jon-doe
spec:
  containers:
  - name: test-container
    image: busybox
    imagePullPolicy: Never
    command: ["sh", "-c"]
    args:
    - while true; do
        if [[ -e /var/labels ]]; then
          echo -en '\n\n'; cat /var/labels; fi;
        if [[ -e /var/annotations ]]; then
          echo -en '\n\n'; cat /var/annotations; fi;
        sleep 3600;
      done;
    volumeMounts:
    - name: podinfo
      mountPath: /var
      readOnly: false
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations